name: random_abstract_avatar
description: 'Random Abstract Avatar lets you generate unique, abstract and customizable user avatars.'
version: 1.1.3
repository: 'https://github.com/Milchkonsument/flutter_random_abstract_avatar'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hashlib: ^1.0.0
